apiVersion: v1
kind: Service
metadata:
  name: generating-service
spec:
  type: ClusterIP
  selector:
    app: generator-pod
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
  labels:
    app: generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: generator-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: generator
          image: generator:1.0.0
          envFrom:
            - secretRef:
                name: generator-secret
          livenessProbe:
            httpGet:
              port: 8000
              path: "/"
          readinessProbe:
            httpGet:
              port: 8000
              path: "/"
          startupProbe:
            httpGet:
              port: 8000
              path: "/"
            initialDelaySeconds: 30
            failureThreshold: 3
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 8000
              name: http
