apiVersion: v1
kind: Service
metadata:
  name: pexel-service
spec:
  type: ClusterIP
  selector:
    app: pexel-pod
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pexel-deployment
  labels:
    app: pexel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pexel-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pexel-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pexel
          image: pexel:1.0.0
          envFrom:
            - secretRef:
                name: pexel-secret
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 8082
              name: http
