insert into quiz (owner_id,name,last_time_used,share_code) values(1,'animals world','2024-05-07','10fd0c28-7f38-4c33-97c0-e4067256ea39');
INSERT INTO question (quiz_id,question) values (1,'cheetah  run even as fast as 110 km per hour');
INSERT INTO question (quiz_id,question) VALUES (1, 'Elephants can swim');
INSERT INTO question (quiz_id,question) VALUES (1, 'Spiders have six legs');
INSERT INTO question (quiz_id,question) VALUES (1, 'Bats are blind');
INSERT INTO question (quiz_id,question) VALUES (1, 'The blue whale is the largest mammal on Earth');
INSERT INTO question (quiz_id,question) VALUES (1, 'Snakes are deaf');
INSERT INTO question (quiz_id,question) VALUES (1, 'Penguins can fly');
INSERT INTO question (quiz_id,question) VALUES (1, 'Greenland shark is the oldest known living animal');
INSERT INTO question (quiz_id,question) VALUES (1, 'Dolphins sleep with one eye open');
INSERT INTO question (quiz_id,question) VALUES (1, 'Bats are the only mammals that can truly fly');

insert into answer (question_id,value,is_correct)  values(1,'yes',true);
insert into answer (question_id,value,is_correct)  values(1,'no',false);
insert into answer (question_id,value,is_correct)  values(2,'yes',true);
insert into answer (question_id,value,is_correct)  values(2,'no',false);
insert into answer (question_id,value,is_correct)  values(3,'yes',false);
insert into answer (question_id,value,is_correct)  values(3,'no',true);
insert into answer (question_id,value,is_correct)  values(4,'yes',false);
insert into answer (question_id,value,is_correct)  values(4,'no',true);
insert into answer (question_id,value,is_correct)  values(5,'yes',true);
insert into answer (question_id,value,is_correct)  values(5,'no',false);
insert into answer (question_id,value,is_correct)  values(6,'yes',false);
insert into answer (question_id,value,is_correct)  values(6,'no',true);
insert into answer (question_id,value,is_correct)  values(7,'yes',false);
insert into answer (question_id,value,is_correct)  values(7,'no',true);
insert into answer (question_id,value,is_correct)  values(8,'yes',true);
insert into answer (question_id,value,is_correct)  values(8,'no',false);
insert into answer (question_id,value,is_correct)  values(9,'yes',true);
insert into answer (question_id,value,is_correct)  values(9,'no',false);
insert into answer (question_id,value,is_correct)  values(10,'yes',true);
insert into answer (question_id,value,is_correct)  values(10,'no',false);

