apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-pod
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: auth
          image: appauth:1.0.0
          envFrom:
            - secretRef:
                name: security-secret
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 8084
              name: http
