apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  type: ClusterIP
  selector:
    app: quiz-pod
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-deployment
  labels:
    app: quiz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: quiz-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: quiz
          image: quiz:1.0.0
          envFrom:
            - secretRef:
                name: quiz-secret
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 8081
              name: http
