apiVersion: v1
kind: Service
metadata:
  name: quiz-headless-service
spec:
  clusterIP: None
  selector:
    app: quiz-db
  ports:
    - port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quiz-stateful-set
spec:
  serviceName: quiz-headless-service
  replicas: 1
  selector:
    matchLabels:
      app: quiz-db
  volumeClaimTemplates:
    - metadata:
        name: quiz-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi
  template:
    metadata:
      labels:
        app: quiz-db
    spec:
      containers:
        - name: quiz-db
          image: postgres:15.0
          envFrom:
            - secretRef:
                name: quiz-secret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: quiz-db-storage
              mountPath: /var/lib/postgresql/data
